name: ros2-talker-listener
version: '0.1'
summary: ROS 2 Talker/Listener Example
description: |
 This example launches a ROS 2 talker and listener.

confinement: devmode
base: core22

apps:
 ros2-talker-listener:
   command: opt/ros/humble/bin/ros2 launch gui gui.launch.py
   extensions:
    - ros2-humble
    - kde-neon
   environment:
      QT_QPA_PLATFORM: xcb

parts:
 ros2-demos:
   plugin: colcon
   source: .
   colcon-packages:
    - gui
   build-packages:
    - ros-humble-ros-core
   stage-packages:
    - ros-humble-ros2launch
    - ros-humble-rclcpp
    - ros-humble-std-msgs
