name: ros2-talker-listener
version: '0.1'
summary: ROS 2 Talker/Listener Example
description: |
 This example launches a ROS 2 talker and listener.

confinement: devmode
base: core22

parts:
 ros2-demos:
   plugin: colcon
   source: .
   build-packages: [make, gcc, g++]
   stage-packages: [ros-humble-ros2launch]

apps:
 ros2-talker-listener:
   command: opt/ros/humble/bin/ros2 launch my_package my_package.launch.py
   extensions: [ros2-humble]
